version: '3.8'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
      - '9095:9095'
    networks:
      - stream
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094,EXTERNAL_CONTAINER://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094,EXTERNAL_CONTAINER://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_CONTAINER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CREATE_TOPICS="logs:1:1"
      # - KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=204800
      # - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=204800
  etl:
    image: 'apache/nifi:latest'
    container_name: etl
    ports:
      - '8443:8443'
      - '8080:8080'
    networks:
      - stream
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
    volumes:
      - ./nifi/templates:/opt/nifi/nifi-current/conf/templates
      - ./nifi/data:/opt/nifi/nifi-current/data
  db:
    image: 'bitnami/elasticsearch'
    container_name: elasticsearch
    networks:
      - stream
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  kibana:
    image: 'bitnami/kibana:latest'
    container_name: kibana
    networks:
      - stream
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kibana_dashboard:/opt/bitnami/kibana/data


networks:
  stream:
    driver: bridge